# -*- coding: utf-8 -*-
"""Mine_Map.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DfWljROy_T8EguAbMLtfoX7j2XtBkqCJ
"""

import matplotlib.pyplot as plt
import random
from matplotlib.ticker import AutoMinorLocator
import numpy as np

# Define the mine characteristics for plotting
mine_Material_Type = {
    'Surface': '#40E0D0',
    'Buried': '#008080'
}

def initialize_map():
    fig, ax = plt.subplots(figsize=(10, 10))
    ax.set_xticks(np.arange(1, 20))  # Set major ticks for x-axis
    ax.set_yticks(np.arange(1, 20))  # Set major ticks for y-axis

    # Adjust x-axis labels
    ax.set_xticklabels(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S'])

    ax.set_aspect('equal')

    # Remove major grid lines
    plt.grid(which='both', color='gray', linestyle='-', linewidth=0)

    # Minor locator for one minor tick between major ticks
    ax.xaxis.set_minor_locator(AutoMinorLocator(2))
    ax.yaxis.set_minor_locator(AutoMinorLocator(2))
    plt.grid(which='minor', color='gray', linestyle='-', linewidth=1)

    # Set fixed axis limits
    ax.set_xlim(0.5, 19.5)
    ax.set_ylim(0.5, 19.5)

    ax.set_xlabel('X Coordinate (A to S)')
    ax.set_ylabel('Y Coordinate (1 to 19)')
    ax.set_title('Mine Detection Map')

    return fig, ax

def update_map(mines, ax):
    for mine in mines:
        x, y, surface_buried = mine
        color = mine_Material_Type[surface_buried]
        ax.scatter(x, y, c=color, marker="s", s=800)
    plt.draw()
    plt.pause(1)

def generate_map(mines):
    fig, ax = initialize_map()
    update_map(mines, ax)
    plt.show()

mines = [(random.randint(1, 19), random.randint(1, 19),
          random.choice(['Surface', 'Buried'])) for _ in range(10)]

generate_map(mines)